<?php

namespace US21\FarmaSaludBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MedicamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentoRepository extends EntityRepository
{
}
